language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
